[project]
name = "llama-index"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langgraph>=1.0.2",
    "langchain-openai>=1.0.2",
    "langchain-huggingface>=1.0.1",
]
